# LaraKube Cloud Pilot — GitLab CI/CD
# Generated by `larakube cloud:configure:gitlab`. Re-run to update.
#
# Required CI/CD variables (set in GitLab → Settings → CI/CD → Variables):
@foreach($cloudEnvs as $envName => $envMeta)
#   {{ $envMeta['upperName'] }}_KUBECONFIG        (masked, base64-encoded kubeconfig)
#   {{ $envMeta['upperName'] }}_ENV_FILE_BASE64   (masked, base64-encoded .env.{{ $envName }})
@endforeach

stages:
  - build
  - deploy

# ── Shared defaults ──────────────────────────────────────────────────────────
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"
@foreach($cloudEnvs as $envName => $envMeta)

# ═══════════════════════════════════════════════════════════════════
# {{ strtoupper($envName) }}
# ═══════════════════════════════════════════════════════════════════

build:{{ $envName }}:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "{{ $envMeta['branch'] }}"'
  before_script:
@if($envMeta['registry'] === 'gitlab')
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
@else
    - echo "${{ '{' }}{{ $envMeta['upperName'] }}_REGISTRY_PASSWORD}" | docker login {{ $envMeta['registry_host'] }} -u "${{ '{' }}{{ $envMeta['upperName'] }}_REGISTRY_USERNAME}" --password-stdin
@endif
  script:
    - |
      # Decode env file and inject Vite build vars
      echo "${{ '{' }}{{ $envMeta['upperName'] }}_ENV_FILE_BASE64}" | base64 -d > .env
      echo "VITE_APP_URL=https://{{ $envMeta['webHost'] }}" >> .env
      echo "VITE_ASSET_URL=https://{{ $envMeta['webHost'] }}" >> .env
    - |
      # Build and push image (BuildKit --secret keeps .env out of layers)
      docker build \
        --secret id=dotenv,src=.env \
        --file Dockerfile.php \
        --target deploy \
        --tag {{ $envMeta['imageLatest'] }} \
        --tag {{ $envMeta['imageSha'] }} \
        .
      docker push {{ $envMeta['imageLatest'] }}
      docker push {{ $envMeta['imageSha'] }}

deploy:{{ $envName }}:
  stage: deploy
  image: registry.k8s.io/kubectl:v1.36.3
  needs: ["build:{{ $envName }}"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "{{ $envMeta['branch'] }}"'
  environment:
    name: {{ $envName }}
  script:
    - |
      # Write kubeconfig
      echo "${{ '{' }}{{ $envMeta['upperName'] }}_KUBECONFIG}" | base64 -d > /tmp/kubeconfig
      export KUBECONFIG=/tmp/kubeconfig

      # Sanity check: refuse to deploy to localhost
      TARGET_URL=$(grep "server:" /tmp/kubeconfig | awk '{print $2}')
      if echo "$TARGET_URL" | grep -qE "127\\.0\\.0\\.1|localhost"; then
        echo "FATAL: Kubeconfig targets localhost ($TARGET_URL). Re-run 'larakube cloud:configure:gitlab'."
        exit 1
      fi

      # Write env file
      echo "${{ '{' }}{{ $envMeta['upperName'] }}_ENV_FILE_BASE64}" | base64 -d > .env

      # Sync env into ConfigMap / Secret
      kubectl create configmap laravel-config \
        -n {{ $envMeta['namespace'] }} --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -
      kubectl create secret generic laravel-secrets \
        -n {{ $envMeta['namespace'] }} --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -

      # Deploy via Kustomize (strip Namespace doc — scoped credentials can't apply it)
      cd .infrastructure/k8s/overlays/{{ $envName }}
      kubectl kustomize . \
        | sed "s|image: {{ $appName }}:{{ $envName }}-latest|image: {{ $envMeta['imageSha'] }}|g" \
        | awk 'function flush(){if(!drop&&doc!=""){printf "%s",doc} doc="";drop=0} /^---[ \t\r]*$/{flush();print;next} {doc=doc $0 "\n"; if($0 ~ /^kind:[ \t]+Namespace[ \t\r]*$/)drop=1} END{flush()}' \
        | kubectl apply -f -

      # Wait for rollout
      kubectl rollout status deployment/{{ $podName }} \
        -n {{ $envMeta['namespace'] }} --timeout=120s
@endforeach
