# LaraKube Cloud Pilot — GitLab CI/CD
# Generated by `larakube cloud:configure:gitlab`. Re-run to update.
#
# Required CI/CD variables (set in GitLab → Settings → CI/CD → Variables):
@foreach($cloudEnvs as $envName => $envMeta)
#   {{ $envMeta['upperName'] }}_KUBECONFIG        (masked, base64-encoded kubeconfig)
@endforeach
# No .env content of any kind is a CI/CD variable — public/build values are
# baked as literal `echo` lines below (computed from your blueprint), and
# runtime secrets only ever reach the cluster via `larakube dotenv:push`,
# run from your own machine.

stages:
  - dependencies
  - build
  - deploy

# ── Shared defaults ──────────────────────────────────────────────────────────
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"
@foreach($cloudEnvs as $envName => $envMeta)

# ═══════════════════════════════════════════════════════════════════
# {{ strtoupper($envName) }}
# ═══════════════════════════════════════════════════════════════════

@php($isPhp = $envMeta['php'] ?? ! ($envMeta['static'] ?? false))
@if($isPhp)
{{-- The image copies the build context, vendor/ included. The dind daemon
     cannot see this job's checkout, so Composer runs as its own job and hands
     vendor/ to the build as an artifact. --}}
composer:{{ $envName }}:
  stage: dependencies
  image: docker.io/library/composer:2.10.3
  rules:
    - if: '$CI_COMMIT_BRANCH == "{{ $envMeta['branch'] }}"'
  script:
    - composer install --no-dev --optimize-autoloader --no-interaction --no-progress --ignore-platform-reqs
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour

@endif
build:{{ $envName }}:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "{{ $envMeta['branch'] }}"'
@if($isPhp)
  needs: ["composer:{{ $envName }}"]
@endif
  before_script:
@if($envMeta['registry'] === 'gitlab')
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
@else
    - echo "${{ '{' }}{{ $envMeta['upperName'] }}_REGISTRY_PASSWORD}" | docker login {{ $envMeta['registry_host'] }} -u "${{ '{' }}{{ $envMeta['upperName'] }}_REGISTRY_USERNAME}" --password-stdin
@endif
  script:
    - |
      # Public/build vars only — computed from your blueprint, never a secret.
      touch .env
      {!! $envMeta['publicEnvScript'] !!}
    - |
      # Build and push image (BuildKit --secret keeps .env out of layers)
      docker build \
        --secret id=dotenv,src=.env \
        --file {{ $envMeta['dockerfile'] ?? (($envMeta['static'] ?? false) ? 'Dockerfile.static' : 'Dockerfile.php') }} \
@if(array_key_exists('target', $envMeta) ? $envMeta['target'] !== null : ! ($envMeta['static'] ?? false))
        --target {{ $envMeta['target'] ?? 'deploy' }} \
@endif
        --tag {{ $envMeta['imageLatest'] }} \
        --tag {{ $envMeta['imageSha'] }} \
        .
      docker push {{ $envMeta['imageLatest'] }}
      docker push {{ $envMeta['imageSha'] }}

deploy:{{ $envName }}:
  stage: deploy
  image: registry.k8s.io/kubectl:v1.37.0
  needs: ["build:{{ $envName }}"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "{{ $envMeta['branch'] }}"'
  environment:
    name: {{ $envName }}
  script:
    - |
      # Write kubeconfig
      echo "${{ '{' }}{{ $envMeta['upperName'] }}_KUBECONFIG}" | base64 -d > /tmp/kubeconfig
      export KUBECONFIG=/tmp/kubeconfig

      # Sanity check: refuse to deploy to localhost
      TARGET_URL=$(grep "server:" /tmp/kubeconfig | awk '{print $2}')
      if echo "$TARGET_URL" | grep -qE "127\\.0\\.0\\.1|localhost"; then
        echo "FATAL: Kubeconfig targets localhost ($TARGET_URL). Re-run 'larakube cloud:configure:gitlab'."
        exit 1
      fi

@if($isPhp)
      # Public/build vars only — computed from your blueprint, never a secret.
      {!! $envMeta['publicEnvScript'] !!}

      # laravel-secrets now only ever comes from `larakube dotenv:push`, run
      # from a developer's own machine — this pipeline never holds runtime
      # credentials, only the public/build vars above. Fail fast with a clear
      # fix instead of letting every pod CrashLoop on a missing envFrom source.
      if ! kubectl get secret laravel-secrets -n {{ $envMeta['namespace'] }} >/dev/null 2>&1; then
        echo "'laravel-secrets' is missing in '{{ $envMeta['namespace'] }}'. Run 'larakube dotenv:push {{ $envName }}' from your machine before deploying."
        exit 1
      fi

      # Sync public config into the ConfigMap (runtime secrets are
      # dotenv:push's job, verified above, never this pipeline's).
      kubectl create configmap laravel-config \
        -n {{ $envMeta['namespace'] }} --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -

@endif
      # Deploy via Kustomize (strip Namespace doc — scoped credentials can't apply it)
      cd .infrastructure/k8s/overlays/{{ $envName }}
      kubectl kustomize . \
        | sed "s|image: {{ $appName }}:{{ $envName }}-latest|image: {{ $envMeta['imageSha'] }}|g" \
        | awk 'function flush(){if(!drop&&doc!=""){printf "%s",doc} doc="";drop=0} /^---[ \t\r]*$/{flush();print;next} {doc=doc $0 "\n"; if($0 ~ /^kind:[ \t]+Namespace[ \t\r]*$/)drop=1} END{flush()}' \
        | kubectl apply -f -

      # Wait for rollout
      kubectl rollout status deployment/{{ $podName }} \
        -n {{ $envMeta['namespace'] }} --timeout=120s
@endforeach
