<?php

namespace App\Traits;

use App\Enums\DatabaseDriver;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Process;

/**
 * Backup inventory and off-site destination config.
 *
 * The inventory is deliberately a declared allow-list rather than "every PVC",
 * because the two are very different sizes and only one of them matters:
 * Prometheus alone is ~4x the size of everything irreplaceable put together,
 * and losing it costs you graphs, not business data.
 *
 * The destination is any S3-compatible endpoint (Cloudflare R2, Backblaze B2,
 * DigitalOcean Spaces, AWS). It must NOT be the cluster's own SeaweedFS — that lives on the
 * same block device as everything it would be backing up, so a disk or droplet
 * loss takes the data and the backups together. See
 * docs/decisions/0010-backup-strategy.md.
 */
trait InteractsWithBackup
{
    use ReadsClusterSecrets;

    /** Where the destination config Secret lives. */
    protected function backupNamespace(): string
    {
        return 'larakube-shared';
    }

    protected function backupKubectl(?string $context = null): string
    {
        $context = (string) ($context ?? '');
        $kubectl = 'KUBECONFIG='.escapeshellarg(home_path('.kube/config')).' kubectl';

        return $context !== '' ? "{$kubectl} --context={$context}" : $kubectl;
    }

    /**
     * Volumes whose contents cannot be rebuilt from anything else.
     *
     * Each entry: the Deployment to exec into, its namespace, the container,
     * and the path to archive. Excluded on purpose:
     *   - prometheus-storage — metrics history, ~1.1G, rebuildable by waiting
     *   - chat-synapse's media_store and site-packages — media is mirrored to
     *     object storage and pip re-installs on every pod start; only the
     *     59-byte signing key matters, and it is captured below
     *   - webmail-storage — regenerated by webmail:init
     *
     * @return array<int, array{name: string, namespace: string, deployment: string, container: string, path: string}>
     */
    protected function backupVolumeTargets(): array
    {
        return [
            // The object store itself. Holds chat media, git LFS, notes, sheets,
            // signed documents and screen recordings — archived whole because
            // SeaweedFS stores volume files, not a browsable tree.
            ['name' => 'seaweedfs', 'namespace' => 'larakube-plex', 'deployment' => 'seaweedfs', 'container' => 'seaweedfs', 'path' => '/data'],
            ['name' => 'openbao', 'namespace' => 'larakube-secrets', 'deployment' => 'openbao-backend', 'container' => 'openbao', 'path' => '/openbao'],
            ['name' => 'forgejo', 'namespace' => 'larakube-shared', 'deployment' => 'forgejo', 'container' => 'forgejo', 'path' => '/data'],
            ['name' => 'drive-ocis', 'namespace' => 'larakube-shared', 'deployment' => 'drive-ocis', 'container' => 'ocis', 'path' => '/var/lib/ocis'],
            ['name' => 'vaultwarden', 'namespace' => 'larakube-vault', 'deployment' => 'vaultwarden', 'container' => 'vaultwarden', 'path' => '/data'],
            ['name' => 'stalwart', 'namespace' => 'larakube-shared', 'deployment' => 'stalwart', 'container' => 'stalwart', 'path' => '/var/lib/stalwart'],
            // Losing this 59-byte key means the homeserver can no longer prove
            // it is the same server: federation and every existing device
            // session break, permanently.
            ['name' => 'synapse-identity', 'namespace' => 'larakube-shared', 'deployment' => 'chat-synapse', 'container' => 'synapse', 'path' => '/data/chat.luchtech.dev.signing.key'],
        ];
    }

    /**
     * Which database engine the Plex Commons is actually running.
     *
     * Read from the plex-commons ConfigMap rather than assumed: Postgres is the
     * common choice but MySQL and MariaDB are equally supported, and a backup
     * that only works on one of them is not a backup for the others.
     */
    protected function commonsDatabaseDriver(string $kubectl, string $plexNamespace = 'larakube-plex'): ?DatabaseDriver
    {
        $raw = Process::timeout(30)->run(
            "{$kubectl} get configmap plex-commons -n {$plexNamespace} -o jsonpath=".escapeshellarg('{.data.commons\.json}'),
        )->output();

        $decoded = json_decode(trim($raw), true);
        $services = is_array($decoded) ? ($decoded['services'] ?? []) : [];

        foreach ($services as $name => $config) {
            if (($config['enabled'] ?? false) !== true) {
                continue;
            }

            $driver = DatabaseDriver::tryFrom((string) $name);

            if ($driver !== null && $driver->hasCommonsDumpCommand()) {
                return $driver;
            }
        }

        return null;
    }

    /**
     * Every non-system database in the Commons, whichever engine it runs.
     *
     * Read live rather than hardcoded so a newly installed tool is covered
     * without a code change — the failure mode of a static list is a database
     * silently not backed up.
     *
     * @return array<int, string>
     */
    protected function backupDatabases(string $kubectl, string $plexNamespace = 'larakube-plex'): array
    {
        $driver = $this->commonsDatabaseDriver($kubectl, $plexNamespace);

        if ($driver === null) {
            return [];
        }

        $service = $driver->commonsServiceName();

        $out = Process::timeout(60)->run(
            "{$kubectl} exec deploy/{$service} -n {$plexNamespace} -c {$service} -- "
            .'sh -c '.escapeshellarg($driver->commonsListDatabasesCommand()),
        )->output();

        return array_values(array_filter(array_map('trim', explode("\n", $out))));
    }

    /**
     * The off-site destination, or null when `backup:init` has not run.
     *
     * @return array{endpoint: string, bucket: string, access_key: string, secret_key: string, passphrase: string, region: string}|null
     */
    protected function readBackupConfig(string $kubectl, string $ns): ?array
    {
        $read = fn (string $key): ?string => $this->readClusterSecretKey($kubectl, $ns, 'larakube-backup-config', $key);

        $bucket = $read('bucket');

        if ($bucket === null || $bucket === '') {
            return null;
        }

        return [
            'endpoint' => $read('endpoint') ?? '',
            'bucket' => $bucket,
            'access_key' => $read('access-key') ?? '',
            'secret_key' => $read('secret-key') ?? '',
            'passphrase' => $read('passphrase') ?? '',
            // "auto" is what R2 requires and what B2/Spaces tolerate, so it is
            // the safest default for a destination we cannot introspect.
            'region' => $read('region') ?? 'auto',
        ];
    }

    /**
     * Environment for every `aws` invocation against the destination.
     *
     * The two checksum settings are not optional. From aws-cli 2.23 the client
     * sends `x-amz-checksum-crc32` on uploads by default, which Cloudflare R2,
     * Backblaze B2 and MinIO reject — the failure surfaces as an opaque
     * signature or "not implemented" error at the moment you most want the
     * backup to work. `when_required` restores the pre-2.23 behaviour.
     *
     * @param  array<string, string>  $config
     * @return array<string, string>
     */
    protected function backupAwsEnv(array $config): array
    {
        return [
            'AWS_ACCESS_KEY_ID' => $config['access_key'],
            'AWS_SECRET_ACCESS_KEY' => $config['secret_key'],
            // R2 wants "auto"; anything else is provider-specific.
            'AWS_DEFAULT_REGION' => $config['region'] !== '' ? $config['region'] : 'auto',
            'AWS_REQUEST_CHECKSUM_CALCULATION' => 'when_required',
            'AWS_RESPONSE_CHECKSUM_VALIDATION' => 'when_required',
        ];
    }

    /**
     * The Cloudflare account ID embedded in an R2 endpoint, or null when the
     * endpoint is not R2. Saves asking for something the user already supplied:
     * R2 endpoints are always https://<account-id>.r2.cloudflarestorage.com.
     */
    protected function r2AccountId(string $endpoint): ?string
    {
        $host = (string) parse_url($endpoint, PHP_URL_HOST);

        if (! str_ends_with($host, '.r2.cloudflarestorage.com')) {
            return null;
        }

        $id = strstr($host, '.', true);

        return is_string($id) && preg_match('/^[0-9a-f]{32}$/', $id) === 1 ? $id : null;
    }

    /**
     * Create an R2 bucket. Idempotent — an existing bucket is success, because
     * re-running `backup:init` against a configured destination is normal.
     *
     * @return array{ok: bool, message: string}
     */
    protected function createR2Bucket(string $accountId, string $bucket, string $token): array
    {
        $response = Http::withToken($token)
            ->timeout(30)
            ->post("https://api.cloudflare.com/client/v4/accounts/{$accountId}/r2/buckets", [
                'name' => $bucket,
            ]);

        $body = $response->json();

        if (($body['success'] ?? false) === true) {
            return ['ok' => true, 'message' => "Created R2 bucket '{$bucket}'."];
        }

        $errors = $body['errors'] ?? [];
        $codes = array_column($errors, 'code');
        $text = implode('; ', array_filter(array_column($errors, 'message')));

        // 10004 is R2's "bucket already exists". Not a failure for us.
        if (in_array(10004, $codes, true) || str_contains(strtolower($text), 'already exists')) {
            return ['ok' => true, 'message' => "R2 bucket '{$bucket}' already exists — reusing it."];
        }

        if ($response->status() === 403 || in_array(10000, $codes, true)) {
            return ['ok' => false, 'message' => 'The token lacks R2 permission. It needs Account · Workers R2 Storage · Edit.'];
        }

        return ['ok' => false, 'message' => $text !== '' ? $text : "Cloudflare returned HTTP {$response->status()}."];
    }

    /**
     * Guard against the most seductive wrong answer: pointing backups at the
     * cluster's own SeaweedFS. It is on the same block device as every volume
     * it would be protecting, so it survives exactly the failures that do not
     * matter and none of the ones that do.
     */
    protected function backupDestinationIsOnCluster(string $endpoint): bool
    {
        return str_contains($endpoint, '.svc.cluster.local')
            || str_contains($endpoint, 'seaweedfs')
            || str_contains($endpoint, 'localhost')
            || str_contains($endpoint, '127.0.0.1');
    }

    /** Everything for one run lives under its own prefix. */
    protected function backupRunPrefix(string $stamp): string
    {
        return "larakube/{$stamp}/";
    }

    /**
     * The manifest is the commit marker, and it is written LAST.
     *
     * Splitting one archive into ~19 objects gives up the property that a
     * backup either lands whole or not at all — a crash mid-upload leaves a
     * prefix holding some of them. Treating a run as real only once its
     * manifest exists restores that: an interrupted run is invisible to
     * backup:list and refused by backup:restore.
     *
     * Do not "optimise" this into being written first.
     */
    protected function manifestKey(string $stamp): string
    {
        return $this->backupRunPrefix($stamp).'manifest.json';
    }

    /**
     * Every run at the destination, from ONE listing.
     *
     * Deliberately not a request per prefix: the listing carries object sizes
     * too, so `backup:list` and the restore picker can both be served without
     * downloading anything.
     *
     * Runs without a manifest are returned with complete=false rather than
     * hidden here — backup:prune needs to see them to clean them up.
     *
     * @param  array<string, string>  $config
     * @return array<string, array{stamp: string, taken: string, bytes: int, objects: array<string, int>, complete: bool}>
     */
    protected function listBackupRuns(array $config): array
    {
        $out = Process::timeout(300)->env($this->backupAwsEnv($config))->run(
            'aws --endpoint-url '.escapeshellarg($config['endpoint'])
            .' s3 ls --recursive '.escapeshellarg("s3://{$config['bucket']}/larakube/"),
        )->output();

        $runs = [];

        foreach (array_filter(array_map('trim', explode("\n", $out))) as $line) {
            $parts = preg_split('/\s+/', $line, 4);

            if ($parts === false || count($parts) < 4) {
                continue;
            }

            [$date, $time, $bytes, $key] = $parts;

            // larakube/<stamp>/<object>. Anything else is from the old
            // single-archive layout, or something we did not write.
            if (! preg_match('#^larakube/([^/]+)/(.+)$#', $key, $m)) {
                continue;
            }

            [, $stamp, $object] = $m;

            $runs[$stamp] ??= ['stamp' => $stamp, 'taken' => "{$date} {$time}", 'bytes' => 0, 'objects' => [], 'complete' => false];
            $runs[$stamp]['objects'][$object] = (int) $bytes;
            $runs[$stamp]['bytes'] += (int) $bytes;

            if ($object === 'manifest.json') {
                $runs[$stamp]['complete'] = true;
                // The manifest is written last, so its timestamp is when the
                // run finished — the honest "taken" time for a job that spans
                // an hour.
                $runs[$stamp]['taken'] = "{$date} {$time}";
            }
        }

        ksort($runs);

        return $runs;
    }

    /**
     * The newest run that actually finished.
     *
     * @param  array<string, string>  $config
     */
    protected function latestCompleteRun(array $config): ?string
    {
        $complete = array_filter($this->listBackupRuns($config), fn (array $r) => $r['complete']);

        return $complete === [] ? null : (string) array_key_last($complete);
    }

    /**
     * Read one run's manifest.
     *
     * Unencrypted on purpose: it is the commit marker, so it has to be cheap to
     * read, and `backup:list` should not need the passphrase. It holds names and
     * sizes only — no data and no credentials — and the tool names it exposes
     * are already visible in the cluster's DNS.
     *
     * @param  array<string, string>  $config
     * @return array{version: int, taken_at: string, engine: string, items: array<int, array{kind: string, name: string, object: string, bytes: int}>}|null
     */
    protected function fetchManifest(array $config, string $stamp): ?array
    {
        $out = Process::timeout(120)->env($this->backupAwsEnv($config))->run(
            'aws --endpoint-url '.escapeshellarg($config['endpoint'])
            .' s3 cp '.escapeshellarg("s3://{$config['bucket']}/".$this->manifestKey($stamp)).' -',
        )->output();

        $decoded = json_decode(trim($out), true);

        return is_array($decoded) && isset($decoded['items']) && is_array($decoded['items'])
            ? $decoded
            : null;
    }

    /**
     * Size of a produced artifact, 0 when absent.
     *
     * A command that exits 0 having written nothing is a real failure mode —
     * `kubectl exec` can succeed while the pod's tar writes to a path that does
     * not exist — so a missing file must read as "empty", not raise.
     */
    protected function sizeOf(string $path): int
    {
        return file_exists($path) ? (int) filesize($path) : 0;
    }

    protected function humanBytes(int $bytes): string
    {
        foreach (['B', 'KB', 'MB', 'GB'] as $unit) {
            if ($bytes < 1024) {
                return round($bytes, 1).$unit;
            }
            $bytes /= 1024;
        }

        return round($bytes, 1).'TB';
    }

    /**
     * The PVC behind a backup target, and where its owning pod mounts it.
     *
     * Restoring a volume means writing into the claim while nothing else has it
     * open, so the helper pod has to mount the claim at the SAME path the real
     * pod uses. The archive was made with `tar -C dirname(path) basename(path)`,
     * which captures the mount point itself as the leading component — extract
     * anywhere else and you get /data/data/… instead of /data/….
     *
     * Longest-prefix wins because a pod can mount a Secret *inside* its data
     * volume (chat-synapse mounts homeserver.yaml under /data), and only the
     * PVC-backed mount is restorable.
     *
     * @param  array<string, string>  $target
     * @return array{claim: string, mountPath: string}|null
     */
    protected function resolveVolumeClaim(string $kubectl, array $target): ?array
    {
        $raw = Process::timeout(60)->run(
            "{$kubectl} get deploy {$target['deployment']} -n {$target['namespace']} -o json",
        )->output();

        $spec = json_decode(trim($raw), true);

        if (! is_array($spec)) {
            return null;
        }

        $pod = $spec['spec']['template']['spec'] ?? [];

        $claims = [];
        foreach ($pod['volumes'] ?? [] as $volume) {
            if (($volume['persistentVolumeClaim']['claimName'] ?? '') !== '') {
                $claims[$volume['name']] = $volume['persistentVolumeClaim']['claimName'];
            }
        }

        $best = null;
        foreach ($pod['containers'] ?? [] as $container) {
            if (($container['name'] ?? '') !== $target['container']) {
                continue;
            }

            foreach ($container['volumeMounts'] ?? [] as $mount) {
                $path = (string) ($mount['mountPath'] ?? '');
                $claim = $claims[$mount['name'] ?? ''] ?? null;

                if ($claim === null || ! str_starts_with($target['path'].'/', rtrim($path, '/').'/')) {
                    continue;
                }

                if ($best === null || strlen($path) > strlen($best['mountPath'])) {
                    $best = ['claim' => $claim, 'mountPath' => $path];
                }
            }
        }

        return $best;
    }
}
