{{-- Next.js production image: build the standalone server, run it on Node.

     Mirrors the official Next.js standalone Dockerfile
     (github.com/vercel/next.js, examples/with-docker). `output: 'standalone'`
     — patched into next.config by `larakube nextjs:new` — emits a
     self-contained server.js with a trimmed node_modules, which the final
     stage copies alongside .next/static and public and runs as `node server.js`.

     Like docker/static.blade.php, the env file is mounted as a BuildKit secret
     for the build only: NEXT_PUBLIC_* values are inlined into the client bundle
     at build time, so .env.production must be readable during `npm run build`
     but must never survive as an image layer (a COPY would bake it in). --}}
############################################
# Dependencies
############################################
FROM node:24-alpine AS dependencies
WORKDIR /app

# libc6-compat: some Next.js/native deps expect glibc on Alpine's musl.
RUN apk add --no-cache libc6-compat

# package.json first: dependencies only reinstall when they actually change.
COPY package*.json ./
RUN npm ci

############################################
# Builder
############################################
FROM node:24-alpine AS builder
WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Generate the Prisma client before the build when a schema is present (the app
# may import @prisma/client). Uses the pinned local prisma from node_modules —
# never npx-fetches a different (RC) version. A no-op for a project without it.
RUN if [ -f prisma/schema.prisma ]; then ./node_modules/.bin/prisma generate; fi

# NEXT_PUBLIC_* are compiled into the bundle here (see header). The env file is
# mounted for this RUN only; a COPY would persist it as a layer. Absent (no
# secret passed), the mount is simply empty and the build still succeeds.
RUN --mount=type=secret,id=dotenv,target=/app/.env.production \
    npm run build

# create-next-app does not always scaffold a public/ dir; guarantee one so the
# final stage's COPY never fails.
RUN mkdir -p public

############################################
# Production Image
############################################
FROM node:24-alpine AS deploy
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Run as the built-in unprivileged `node` user (uid 1000), per Next.js guidance.
# .next is pre-created and owned so the standalone server can write its cache.
RUN mkdir .next && chown node:node .next

# output: 'standalone' — the traced server plus its trimmed node_modules, then
# the static assets and public/ files it serves.
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static
COPY --from=builder --chown=node:node /app/public ./public

# Distributed ISR/RSC Redis cache handler generated by `larakube nextjs:new`.
# Shipped alongside server.js so next.config's `cacheHandler` can point at it.
COPY --from=builder --chown=node:node /app/cache-handler.mjs ./cache-handler.mjs

# Prisma schema for the migrate init container (`prisma@6 migrate deploy`);
# standalone trims it out of the traced output, so copy it explicitly.
COPY --from=builder --chown=node:node /app/prisma ./prisma

USER node
EXPOSE 3000

# The Next.js standalone entrypoint.
CMD ["node", "server.js"]
